# Template for Compilation & Tests in GitLab CI
# image: nickgryg/alpine-pandas
image: devops.telecomste.fr:5050/printerfaceadmin/2022-23/group8/image

# variables:
#   - IMAGE: devops.telecomste.fr:5050/printerfaceadmin/2022-23/group8/image

# include all the before script in a requirement file
before_script:
  # - apt-get install python3-dev
  # - docker login -u ... -p $CI_JOB_TOKEN

  
stages:
  - build
  - compile
  - pylint
  - coverage
  - test
  - delivery

# build:
#   -stage: build
#   -script:
#     - docker build -t $IMAGE -f docker/Dockerfile .
#     - docker tag $IMAGE $IMAGE:test
#     - docker push $IMAGE


compile:
  stage: compile
  script:
  - echo "Here goes my compile command [NOT IMPLEMENTED YET]"

pylint:
  stage : pylint
  script : pylint script/web_app/app.py --fail-under=8
 
coverage :
  stage : coverage
  script : 
    - cd script/web_app/
    - pwd
    - coverage run -m unittest /builds/printerfaceadmin/2022-23/group8/script/web_app/*.py
    - coverage report # | grep -E "/^\s*TOTAL\s+\d+\s+\d+\s+\d+%/gm" | grep -E "^(.{2})*%"
    
  
  
# test:
#   stage: test
#   script:
#   - python3 -m unittest test.py

# delivery :
#   stage : delivery
#   script :
#     - 
#   only : 
#     refs:
#       - master
