# Template for Compilation & Tests in GitLab CI
image: python:3.8-alpine

# include all the before script in a requirement file
before_script:
  - python --version
  - pip install -r requirements.txt
  
stages:
  - compile
  - pylint
  - test
#  - coverage
#  - deploy

compile:
  stage: compile
  script:
  - echo "Here goes my compile command [NOT IMPLEMENTED YET]"

pylint:
  stage : pylint
  script: pylint script/
  #- echo "Checking for code quality [NOT IMPLEMENTED YET]"

test:
  stage: test
  script:
  - echo "Running unit tests [NOT IMPLEMENTED YET]"
  - python3 -m unittest test_get_infos.py




# Step below are not useful for the moment

#staging:
#  stage: deploy
#  script:
#  - echo "Deploying application on production environnement [NOT IMPLEMENTED YET]"
#  only:
#  - master

#production:
#  stage: deploy
#  script:
#  - echo "Deploying application on pre-production environnement [NOT IMPLEMENTED YET]"
#  only:
#  - develop

#lint:
#  stage: lint
#  script:

#coverage:
#  stage: coverage
#  script:
#  - echo "Checking for code coverage level [NOT IMPLEMENTED YET]"


